### ISSUE TITLE
P25 図1.15 「snippetを追加」画面のように投稿日が表示されない

### ISSUE THREAD

**Issue by LittleBear-6w6** [c-bata/practical-django-book#1]
１ 章・25ページ

* 章: <1>
* ページ: <25>
* : 初版

## 内容
図1.15で投稿日が画面表示されていますが、手元の環境で試したところ投稿日は画面表示されませんでした。
これは、P21 リスト1.13 snippets/models.pyのcrerated_atの定義が「auto_new_add=True」で自動入力となっていて自ら設定できないからだと考えましたが、いかがでしょうか？

```python:snippets/models.py 抜粋
created_at = models.DateTimeField("投稿日", auto_now_add=True)
```

＜実行環境＞
・Linux
・Python 3.8.10
・Django 3.2.7

![ハンズオン結果_snippet追加画面](https://user-images.githubusercontent.com/57203646/132981418-9434bd47-a42f-4e5a-b4be-5ec50af11e08.png)

**Comment by c-bata** [comment]
ご報告ありがとうございます。こちらおっしゃるとおりです :bow:
スクリーンショットの画像が間違っているようですので、次のように修正させていただきます。

**修正前:**
![admin-add-snippet](https://user-images.githubusercontent.com/5564044/133934359-c3ad83ba-b321-496d-8804-42f77468232c.png)

**修正後**
<img width="1044" alt="実践Django_p25_図1 15_正" src="https://user-images.githubusercontent.com/5564044/133934320-a0f5083a-fb22-4bf0-bdf6-68550bb80246.png">


出版社にはこちらから報告しておきます。
本書のご購入、誤記のご報告ありがとうございました。

**Comment by LittleBear-6w6** [comment]
ご回答ありがとうございます。
少しずつハンズオンを進めて、Djangoを習得したいと思います。
